version: '3.8'

services:
  flask:
    build:
      context: ./Backend
      dockerfile: Dockerfile  # Adjust if your Dockerfile is named differently
    privileged: true
    expose:
      - "8000"
    # volumes:
    #   - /dev/pts/6:/dev/ttyUSB0
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"  # Map the serial port device
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production  # Optional: set environment variables
    restart: unless-stopped

  angular:
    build:
      context: ./Spa # Path to your Angular project
      dockerfile: Dockerfile  # Adjust if your Dockerfile is named differently
    expose:
      - "80"  # Expose Angular internally
    restart: unless-stopped

  nginx:
    build:
      context: ./Proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Expose Nginx on port 80
    depends_on:
      - angular
      - flask
    restart: unless-stopped

  udp-server:
    build:
      context: ./Udp
      dockerfile: Dockerfile
    network_mode: host
    restart: unless-stopped